.TH "_PICC_Args" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scheduler\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Error\fP * \fBerror\fP"
.br
.ti -1c
.RI "\fBPICC_SchedPool\fP * \fBsched_pool\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The args taken by the slave scheduler function during the posix thead creation in the main entry point\&. 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Error\fP* _PICC_Args::error"
The errors list 
.SS "\fBPICC_SchedPool\fP* _PICC_Args::sched_pool"
a pointer to the scheduler data 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
