.TH "_PICC_Channel" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Channel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <channel\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "struct \fB_PICC_Commit\fP * \fBincommits\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Commit\fP * \fBoutcommits\fP"
.br
.ti -1c
.RI "int \fBglobal_rc\fP"
.br
.ti -1c
.RI "\fBPICC_Mutex\fP \fBlock\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The type of the pi-thread channels 
.SH "Field Documentation"
.PP 
.SS "int _PICC_Channel::global_rc"

.SS "struct \fB_PICC_Commit\fP* _PICC_Channel::incommits"
The input commits list 
.SS "\fBPICC_Mutex\fP _PICC_Channel::lock"
The number of commitments to that reference this channel (TODO see spec) 
.SS "struct \fB_PICC_Commit\fP* _PICC_Channel::outcommits"
The output commits list 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
