.TH "_PICC_Queue" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_QueueCell\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBPICC_QueueCell\fP * \fBtail\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The standard PiThread queue type 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_QueueCell\fP* _PICC_Queue::head"
The head of the queue 
.SS "int _PICC_Queue::size"
The size of the queue 
.SS "\fBPICC_QueueCell\fP* _PICC_Queue::tail"
The tail of the queue 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
