.TH "_PICC_Commit" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Commit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commit\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBPICC_InCommit\fP * \fBin\fP"
.br
.ti -1c
.RI "   \fBPICC_OutCommit\fP * \fBout\fP"
.br
.ti -1c
.RI "} \fBcontent\fP"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_CommitType\fP \fBtype\fP"
.br
.ti -1c
.RI "struct \fB_PICC_PiThread\fP * \fBthread\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Clock\fP * \fBclock\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Value\fP * \fBclockval\fP"
.br
.ti -1c
.RI "\fBPICC_Label\fP \fBcont_pc\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Channel\fP * \fBchannel\fP"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in -1c
.SH "Detailed Description"
.PP 
The commitment common part 
.SH "Field Documentation"
.PP 
.SS "struct \fB_PICC_Channel\fP* _PICC_Commit::channel"
The channel of this commitment 
.SS "struct \fB_PICC_Clock\fP* _PICC_Commit::clock"
The pi-thread that has this commit 
.SS "struct \fB_PICC_Value\fP* _PICC_Commit::clockval"
The time when the commitment has been made TODO see spec 
.SS "\fBPICC_Label\fP _PICC_Commit::cont_pc"
TODO see spec 
.SS "union { \&.\&.\&. }   _PICC_Commit::content"

.SS "\fBPICC_InCommit\fP* _PICC_Commit::in"
The in commitment specific part 
.SS "\fBPICC_OutCommit\fP* _PICC_Commit::out"
The out commitment specific part 
.SS "struct \fB_PICC_PiThread\fP* _PICC_Commit::thread"

.SS "\fBPICC_CommitType\fP _PICC_Commit::type"
The type of the commit 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
