.TH "_PICC_KnownsSet" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_KnownsSet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <channel\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Knowns\fP ** \fBknowns\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The set of known channels 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Knowns\fP** _PICC_KnownsSet::knowns"

.SS "int _PICC_KnownsSet::length"
A pointer to an array of knowns\&. Contains all the data The size of the set 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
