.TH "_PICC_CommitList" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_CommitList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commit\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_CommitListElement\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBPICC_CommitListElement\fP * \fBtail\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The commit list type 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_CommitListElement\fP* _PICC_CommitList::head"
The head of the commit list 
.SS "int _PICC_CommitList::size"
The size of the commit list 
.SS "\fBPICC_CommitListElement\fP* _PICC_CommitList::tail"
The tail of the commit list 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
