.TH "_PICC_SchedPool" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_SchedPool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scheduler\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "struct \fB_PICC_ReadyQueue\fP * \fBready\fP"
.br
.ti -1c
.RI "struct \fB_PICC_WaitQueue\fP * \fBwait\fP"
.br
.ti -1c
.RI "\fBPICC_Mutex\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBPICC_Condition\fP \fBcond\fP"
.br
.ti -1c
.RI "int \fBnb_slaves\fP"
.br
.ti -1c
.RI "int \fBnb_waiting_slaves\fP"
.br
.ti -1c
.RI "bool \fBrunning\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
This type contains all the scheduler data 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Condition\fP _PICC_SchedPool::cond"

.SS "\fBPICC_Mutex\fP _PICC_SchedPool::lock"
The queue that contains the waiting or blocked pi-threads The scheduler lock\&. TODO see spec 
.SS "int _PICC_SchedPool::nb_slaves"
The scheduler condition\&. Used to synchronise the running posix threads\&. 
.SS "int _PICC_SchedPool::nb_waiting_slaves"
The number of running posix threads in the schedpool\&. The number of waiting posix threads\&. 
.SS "struct \fB_PICC_ReadyQueue\fP* _PICC_SchedPool::ready"

.SS "bool _PICC_SchedPool::running"
Specifies if the scheduler is actually running 
.SS "struct \fB_PICC_WaitQueue\fP* _PICC_SchedPool::wait"
The queue that contains the pi-threads ready tuo run 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
