.TH "_PICC_ReadyQueue" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_ReadyQueue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Queue\fP \fBq\fP"
.br
.ti -1c
.RI "\fBPICC_Mutex\fP \fBlock\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The ready PiThread queue type 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Mutex\fP _PICC_ReadyQueue::lock"
The standard PiThread queue that contains all the data 
.SS "\fBPICC_Queue\fP _PICC_ReadyQueue::q"


.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
