.TH "_PICC_Clock" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Clock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <value\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_AtomicInt\fP * \fBval\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A type to represent PiThread clocks 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_AtomicInt\fP* _PICC_Clock::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
