.TH "_PICC_CommitListElement" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_CommitListElement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commit\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Commit\fP * \fBcommit\fP"
.br
.ti -1c
.RI "struct \fB_PICC_CommitListElement\fP * \fBnext\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The type of an element of a commit list 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Commit\fP* _PICC_CommitListElement::commit"
The referenced commit 
.SS "struct \fB_PICC_CommitListElement\fP* _PICC_CommitListElement::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
