.TH "_PICC_Knowns" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_Knowns \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <channel\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Channel\fP * \fBchannel\fP"
.br
.ti -1c
.RI "\fBPICC_KnownsState\fP \fBstate\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The type of a channel with a known state 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Channel\fP* _PICC_Knowns::channel"
a reference to the tracked channel 
.SS "\fBPICC_KnownsState\fP _PICC_Knowns::state"
the known state 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
