.TH "_PICC_SetElement" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_SetElement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <set\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPICC_SetType\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBPICC_Commit\fP * \fBc\fP"
.br
.ti -1c
.RI "   \fBPICC_Knowns\fP * \fBk\fP"
.br
.ti -1c
.RI "} \fBelement\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Commit\fP* _PICC_SetElement::c"

.SS "union { \&.\&.\&. }   _PICC_SetElement::element"

.SS "\fBPICC_Knowns\fP* _PICC_SetElement::k"

.SS "\fBPICC_SetType\fP _PICC_SetElement::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
