.TH "_PICC_QueueCell" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_QueueCell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "struct \fB_PICC_PiThread\fP * \fBthread\fP"
.br
.ti -1c
.RI "struct \fB_PICC_QueueCell\fP * \fBnext\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The standard PiThread queue cell type 
.SH "Field Documentation"
.PP 
.SS "struct \fB_PICC_QueueCell\fP* _PICC_QueueCell::next"
The pi-thread contained in the cell 
.SS "struct \fB_PICC_PiThread\fP* _PICC_QueueCell::thread"


.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
