.TH "_PICC_PiThread" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_PiThread \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pi_thread\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_StatusKind\fP \fBstatus\fP"
.br
.ti -1c
.RI "bool * \fBenabled\fP"
.br
.ti -1c
.RI "int \fBenabled_length\fP"
.br
.ti -1c
.RI "struct \fB_PICC_KnownsSet\fP * \fBknowns\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Value\fP ** \fBenv\fP"
.br
.ti -1c
.RI "int \fBenv_length\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Commit\fP * \fBcommit\fP"
.br
.ti -1c
.RI "struct \fB_PICC_CommitList\fP * \fBcommits\fP"
.br
.ti -1c
.RI "\fBPICC_PiThreadProc\fP * \fBproc\fP"
.br
.ti -1c
.RI "\fBPICC_Label\fP \fBpc\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Value\fP * \fBval\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Clock\fP * \fBclock\fP"
.br
.ti -1c
.RI "int \fBfuel\fP"
.br
.ti -1c
.RI "\fBPICC_Mutex\fP \fBlock\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The PiThread data type 
.SH "Field Documentation"
.PP 
.SS "struct \fB_PICC_Clock\fP* _PICC_PiThread::clock"
The last transmited lalue over the current channel 
.SS "struct \fB_PICC_Commit\fP* _PICC_PiThread::commit"

.SS "struct \fB_PICC_CommitList\fP* _PICC_PiThread::commits"
The last commitment of the pi-thread 
.SS "bool* _PICC_PiThread::enabled"
TODO see spec 
.SS "int _PICC_PiThread::enabled_length"

.SS "struct \fB_PICC_Value\fP** _PICC_PiThread::env"
The local pi-thread variables 
.SS "int _PICC_PiThread::env_length"
The number of variables in the environment 
.SS "int _PICC_PiThread::fuel"
The pi-tjread clock\&. TODO see spec 
.SS "struct \fB_PICC_KnownsSet\fP* _PICC_PiThread::knowns"
Length of enabeled choices at the next step TODO see spec 
.SS "\fBPICC_Mutex\fP _PICC_PiThread::lock"
Number of iterations of the pi-thread execution after wich the garbage collector tries to free some space 
.SS "\fBPICC_Label\fP _PICC_PiThread::pc"
The pi-thread procedure to execute 
.SS "\fBPICC_PiThreadProc\fP* _PICC_PiThread::proc"
The commitments of this pi-thread 
.SS "\fBPICC_StatusKind\fP _PICC_PiThread::status"
The pi-thread status 
.SS "struct \fB_PICC_Value\fP* _PICC_PiThread::val"
The label to the execution point of the pi-thread procedure 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
