.TH "_PICC_WaitQueue" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PICC_WaitQueue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPICC_Queue\fP \fBactive\fP"
.br
.ti -1c
.RI "\fBPICC_Queue\fP \fBold\fP"
.br
.ti -1c
.RI "\fBPICC_Mutex\fP \fBlock\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
The wait PiThread queue type 
.SH "Field Documentation"
.PP 
.SS "\fBPICC_Queue\fP _PICC_WaitQueue::active"

.SS "\fBPICC_Mutex\fP _PICC_WaitQueue::lock"
The standard queue that contains the PiThreads that are waiting a lot of time 
.SS "\fBPICC_Queue\fP _PICC_WaitQueue::old"
The standard queue that contains the PiThreads that are not waiting for a long time 

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
