.TH "src/main.c" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <tools\&.h>\fP
.br
\fC#include <commit\&.h>\fP
.br
\fC#include <channel\&.h>\fP
.br
\fC#include <set\&.h>\fP
.br
\fC#include <pi_thread\&.h>\fP
.br
\fC#include <runtime\&.h>\fP
.br
\fC#include <errors\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main for generic sets tests\&.
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Maxence WO 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
