.TH "md_README" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- libpirt 
multithreaded runtime environment for the pi compiler
.PP
.SH "Authors"
.PP
.PP
.IP "\(bu" 2
Mickaël Menu (mickael.menu@gmail.com)
.IP "\(bu" 2
Maxence WO (darkmaxounet@gmail.com)
.IP "\(bu" 2
Dany Siriphol (dany.siriphol@gmail.com)
.IP "\(bu" 2
Loïc Girault (loic.girault@gmail.com)
.IP "\(bu" 2
Joël Hing (hing.joel@gmail.com)
.IP "\(bu" 2
Florian Thibord (florian.thibord@gmail.com)
.IP "\(bu" 2
Sergiu Tiganu (postaserg@gmail.com) 
.PP

