.TH "tests/runtime_test.c" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/runtime_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <pi_thread\&.h>\fP
.br
\fC#include <runtime\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcheck_pithread\fP (\fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "bool \fBcheck_commits\fP (\fBPICC_Error\fP *error)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool check_commits (\fBPICC_Error\fP *error)"
Test : Commitments 
.br
 PICC_Commit *PICC_create_commitment(); 
.br
 PICC_CommitList *PICC_create_commit_list(); 
.br
 PICC_CommitListElement *PICC_create_commit_list_element();
.PP
plop
.PP
\fBReturns:\fP
.RS 4
boolean true if it works else false 
.RE
.PP

.SS "bool check_pithread (\fBPICC_Error\fP *error)"
Test : PICC_create_pithread 
.br
 PICC_PiThread *PICC_create_pithread();
.PP
\fBReturns:\fP
.RS 4
boolean true if it works else false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
