.TH "src/runtime.c" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/runtime.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include <runtime\&.h>\fP
.br
\fC#include <queue\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPICC_GC2\fP (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "void \fBPICC_main\fP (int nb_core_threads, \fBPICC_PiThreadProc\fP entrypoint)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File that contains definitions of the prototypes specified in \fBruntime\&.h\fP
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Maxence WO 
.PP
Dany SIRIPHOL 
.PP
Joel HING 
.PP
Mickaël MENU
.RE
.PP
File that contains all the necesseray tests to check the behavior of all functions of \fBruntime\&.c\fP
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Maxence WO 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int PICC_GC2 (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *error)"
Temporary main entry point\&. Second generation garbage collector\&.
.PP
\fBParameters:\fP
.RS 4
\fIschedpool\fP The schedpool to clean 
.br
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
? ???????????????? 
.RE
.PP

.SS "void PICC_main (intnb_core_threads, \fBPICC_PiThreadProc\fPentrypoint)"
The entry point of the Runtime library\&. Initialises the real running threads and starts the scheduler
.PP
\fBParameters:\fP
.RS 4
\fInb_core_threads\fP Maximum number of core threads that can run at the same time 
.br
\fIentrypoint\fP Entry procedure the for the first thread 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
