.TH "include/runtime.h" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/runtime.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <scheduler\&.h>\fP
.br
\fC#include <pi_thread\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPICC_GC2\fP (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "void \fBPICC_main\fP (int nb_core_threads, \fBPICC_PiThreadProc\fP *entrypoint)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File that contains headers of the runtime functions specified in the specification's document\&.
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Maxence WO 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int PICC_GC2 (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *error)"
Temporary main entry point\&. Second generation garbage collector\&.
.PP
\fBParameters:\fP
.RS 4
\fIschedpool\fP The schedpool to clean 
.br
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
? ???????????????? 
.RE
.PP

.SS "void PICC_main (intnb_core_threads, \fBPICC_PiThreadProc\fP *entrypoint)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
