.TH "include/scheduler.h" 3 "Fri Feb 8 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/scheduler.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue\&.h>\fP
.br
\fC#include <sync\&.h>\fP
.br
\fC#include <error\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_PICC_SchedPool\fP"
.br
.ti -1c
.RI "struct \fB_PICC_Args\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_PICC_SchedPool\fP \fBPICC_SchedPool\fP"
.br
.ti -1c
.RI "typedef struct \fB_PICC_Args\fP \fBPICC_Args\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPICC_SchedPool\fP * \fBPICC_create_sched_pool\fP (\fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "\fBPICC_Args\fP * \fBPICC_create_args\fP (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *err, \fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "void \fBPICC_sched_pool_slave\fP (\fBPICC_Args\fP *args)"
.br
.ti -1c
.RI "void \fBPICC_sched_pool_master\fP (\fBPICC_SchedPool\fP *sp, int std_gc_fuel, int quick_gc_fuel, int active_factor, \fBPICC_Error\fP *error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Schedulers\&.
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Mickaël MENU 
.PP
Maxence WO 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_PICC_Args\fP  \fBPICC_Args\fP"
The args taken by the slave scheduler function during the posix thead creation in the main entry point\&. 
.SS "typedef struct \fB_PICC_SchedPool\fP  \fBPICC_SchedPool\fP"
This type contains all the scheduler data 
.SH "Function Documentation"
.PP 
.SS "\fBPICC_Args\fP* PICC_create_args (\fBPICC_SchedPool\fP *sp, \fBPICC_Error\fP *err, \fBPICC_Error\fP *error)"
Creates a new set of arguments to passe to a scheduler\&.
.PP
\fBParameters:\fP
.RS 4
\fIsp\fP Scheduler pool 
.br
\fIerr\fP Scheduler error stack 
.br
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created set of arguments 
.RE
.PP

.SS "\fBPICC_SchedPool\fP* PICC_create_sched_pool (\fBPICC_Error\fP *error)"
Creates a new scheduler\&.
.PP
\fBParameters:\fP
.RS 4
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created scheduler 
.RE
.PP

.SS "void PICC_sched_pool_master (\fBPICC_SchedPool\fP *sp, intstd_gc_fuel, intquick_gc_fuel, intactive_factor, \fBPICC_Error\fP *error)"
????????????????????
.PP
\fBParameters:\fP
.RS 4
\fIsp\fP ???????????????? 
.br
\fIstd_gc_fuel\fP ??????????????? 
.br
\fIquick_gc_fuel\fP ????????????? 
.br
\fIactive_factor\fP ????????????? 
.br
\fIerror\fP Error stack 
.RE
.PP

.SS "void PICC_sched_pool_slave (\fBPICC_Args\fP *args)"
Handles the behavior of a scheduler pool\&.
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP Arguments containing the scheduler pool and the error stack 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
