.TH "tests/set_test.c" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/set_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <tools\&.h>\fP
.br
\fC#include <commit\&.h>\fP
.br
\fC#include <channel\&.h>\fP
.br
\fC#include <set\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprinter\fP (\fBPICC_Set\fP *commit_set)"
.br
.ti -1c
.RI "void \fBtest_map\fP (void *c)"
.br
.ti -1c
.RI "void \fBtest_map2\fP (\fBPICC_Commit\fP *c)"
.br
.ti -1c
.RI "int \fBPICC_test_generic_sets\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic sets tests\&.
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Maxence WO 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG"

.SH "Function Documentation"
.PP 
.SS "int PICC_test_generic_sets ()"

.SS "void printer (\fBPICC_Set\fP *commit_set)"

.SS "void test_map (void *c)"

.SS "void test_map2 (\fBPICC_Commit\fP *c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
