.TH "src/value.c" 3 "Fri Jan 25 2013" "PiThread" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/value.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <value\&.h>\fP
.br
\fC#include <tools\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPICC_Value\fP * \fBPICC_create_value\fP (\fBPICC_ValueKind\fP type, \fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "\fBPICC_AtomicBoolean\fP * \fBPICC_create_atomic_boolean\fP (\fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "\fBPICC_AtomicInt\fP * \fBPICC_create_atomic_int\fP (\fBPICC_Error\fP *error)"
.br
.ti -1c
.RI "\fBPICC_Clock\fP * \fBPICC_create_clock\fP (\fBPICC_Error\fP *error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Values exchanged through the program\&.
.PP
This project is released under MIT License\&.
.PP
\fBAuthor:\fP
.RS 4
Mickaël MENU 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBPICC_AtomicBoolean\fP* PICC_create_atomic_boolean (\fBPICC_Error\fP *error)"
Creates an atomic boolean\&.
.PP
\fBParameters:\fP
.RS 4
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created atomic boolean 
.RE
.PP

.SS "\fBPICC_AtomicInt\fP* PICC_create_atomic_int (\fBPICC_Error\fP *error)"
Creates an atomic integer\&.
.PP
\fBParameters:\fP
.RS 4
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created atomic integer 
.RE
.PP

.SS "\fBPICC_Clock\fP* PICC_create_clock (\fBPICC_Error\fP *error)"
Creates a new clock\&.
.PP
\fBParameters:\fP
.RS 4
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created clock 
.RE
.PP

.SS "\fBPICC_Value\fP* PICC_create_value (\fBPICC_ValueKind\fPtype, \fBPICC_Error\fP *error)"
Creates a new value of given type\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP Type of the value 
.br
\fIerror\fP Error stack 
.RE
.PP
\fBReturns:\fP
.RS 4
Created value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PiThread from the source code\&.
